import java.io.*;
import java.net.*;
import java.util.regex.*;

public class NCatCompute {
    public static void main(String[] args) {
         // If there are missing inputs, inform the user and exit
        if (args.length < 2) {
            // Informs the user then exits
            System.out.println("One or more required inputs is missing");
            return;
        }
        final String regex = "\\d{1,} \\+ \\d{1,}";
        final String flag = "247CTF\\{.*\\}";
        
        InetAddress netAddress;
        try {
            // Attempts to get ip from the hostname of the server
            netAddress = InetAddress.getByName(args[0]);
        } catch (UnknownHostException e) {
            // If host is not found exit
            System.err.println("Unknown name for ip");
            return;
        }

        Socket client;
        try {
            // Create a socket using the found host, and the port generated by the server
            client = new Socket(netAddress, Integer.parseInt(args[1]));
            // Created a reader off the bytestream coming from the socket
            BufferedReader reader = new BufferedReader(new InputStreamReader(client.getInputStream()));
            BufferedWriter writer = new BufferedWriter(new OutputStreamWriter(client.getOutputStream()));
            Pattern pattern1 = Pattern.compile(flag, Pattern.MULTILINE);
            Pattern pattern2 = Pattern.compile(regex, Pattern.MULTILINE);
            Matcher match1;
            Matcher match2;
            String data;
            // Loop until all data is recieved
            while(true) {
                // Gets the next line of data from the bufferedreader
                data = reader.readLine();
                System.out.println(data);
                // If the next line is null, exit the loop
                if (data == null) { break; }
                match1 = pattern1.matcher(data);
                if (match1.find()) {
                    System.out.println(match1.group());
                    break;
                }
                match2 = pattern2.matcher(data);
                // If the data matches the regex, send it back to the server
                if (match2.find()) {
                    String[] numbers = match2.group().split(" \\+ ");
                    int sum = Integer.parseInt(numbers[0]) + Integer.parseInt(numbers[1]);
                    writer.write(String.valueOf(sum));
                    writer.newLine();
                    writer.flush();
                }
            }
            System.out.println("Done");
            // Close the connection
            client.close();
        // Catch any unexpected errors
        } catch (Exception e) {
            System.err.println(e);
        }
    }
}
